package flow

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ErrNotFound is returned when a flow does not exist for the given tenant+id.
var ErrNotFound = errors.New("flow not found")

// ErrExpired is returned when a pending flow has passed its expiry time.
var ErrExpired = errors.New("flow expired")

// Store provides DB-backed access to self_service_flows.
type Store struct {
	pool *pgxpool.Pool
}

// NewStore constructs a Store.
func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{pool: pool}
}

// Create inserts a new flow and returns the persisted row.
// The flow ID is generated by the database.
func (s *Store) Create(ctx context.Context, tenantID uuid.UUID, flowType Type, ui UI, expiresAt time.Time) (*Flow, error) {
	uiJSON, err := json.Marshal(ui)
	if err != nil {
		return nil, fmt.Errorf("flow.Create marshal ui: %w", err)
	}

	var f Flow
	var uiRaw []byte
	err = s.pool.QueryRow(ctx, `
		INSERT INTO self_service_flows (tenant_id, type, state, ui, expires_at)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, tenant_id, type, state, identity_id, ui, expires_at
	`, tenantID, string(flowType), string(StatePending), uiJSON, expiresAt).
		Scan(&f.ID, &f.TenantID, &f.Type, &f.State, &f.IdentityID, &uiRaw, &f.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("flow.Create: %w", err)
	}

	if err := json.Unmarshal(uiRaw, &f.UI); err != nil {
		return nil, fmt.Errorf("flow.Create decode ui: %w", err)
	}
	return &f, nil
}

// Get returns a flow by tenant+id. Returns ErrNotFound or ErrExpired as sentinel errors.
func (s *Store) Get(ctx context.Context, tenantID, flowID uuid.UUID) (*Flow, error) {
	var f Flow
	var uiRaw []byte
	err := s.pool.QueryRow(ctx, `
		SELECT id, tenant_id, type, state, identity_id, ui, expires_at
		FROM self_service_flows
		WHERE tenant_id = $1 AND id = $2
	`, tenantID, flowID).
		Scan(&f.ID, &f.TenantID, &f.Type, &f.State, &f.IdentityID, &uiRaw, &f.ExpiresAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, fmt.Errorf("flow.Get %s: %w", flowID, ErrNotFound)
	}
	if err != nil {
		return nil, fmt.Errorf("flow.Get %s: %w", flowID, err)
	}

	if err := json.Unmarshal(uiRaw, &f.UI); err != nil {
		return nil, fmt.Errorf("flow.Get decode ui %s: %w", flowID, err)
	}

	if f.State == StatePending && time.Now().After(f.ExpiresAt) {
		// Best-effort state update; ignore write error since we return ErrExpired either way.
		_ = s.UpdateState(ctx, tenantID, flowID, StateExpired)
		return nil, fmt.Errorf("flow.Get %s: %w", flowID, ErrExpired)
	}
	return &f, nil
}

// Update overwrites the state, identity_id, and ui of a flow atomically.
func (s *Store) Update(ctx context.Context, tenantID, flowID uuid.UUID, state State, identityID *uuid.UUID, ui UI) error {
	uiJSON, err := json.Marshal(ui)
	if err != nil {
		return fmt.Errorf("flow.Update marshal ui: %w", err)
	}

	tag, err := s.pool.Exec(ctx, `
		UPDATE self_service_flows
		SET state = $3, identity_id = $4, ui = $5
		WHERE tenant_id = $1 AND id = $2
	`, tenantID, flowID, string(state), identityID, uiJSON)
	if err != nil {
		return fmt.Errorf("flow.Update %s: %w", flowID, err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("flow.Update %s: %w", flowID, ErrNotFound)
	}
	return nil
}

// UpdateState changes only the state column of a flow.
func (s *Store) UpdateState(ctx context.Context, tenantID, flowID uuid.UUID, state State) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE self_service_flows
		SET state = $3
		WHERE tenant_id = $1 AND id = $2
	`, tenantID, flowID, string(state))
	if err != nil {
		return fmt.Errorf("flow.UpdateState %s: %w", flowID, err)
	}
	return nil
}
